### ISSUE TITLE
Auth, push and update

### ISSUE THREAD

**Issue by jgmatu** [shaggyshelar/node-red-contrib-google-firebase#1]
Good morning,

Have you got in mind add features of auth to the proyect?

Can I make a pull request if I develop this features?

My problem is I need use database auth with google firebase, I think is good idea add the parameters
email and password to node firebase config to realize the auth in the database.

¿How do you see?

Thanks!

**Comment by mr-sagar-shelar** [comment]
Hey, Sure you can make pull request.
Actually I wanted to develop it completely but couldn't spend much time.

**Comment by mr-sagar-shelar** [comment]
Your pull request has been merged.
