### ISSUE TITLE
msg.childpath not working

### ISSUE THREAD

**Issue by megazero1316** [shaggyshelar/node-red-contrib-google-firebase#3]
Hello

today i tried your library and found that if i want to set the path using msg.childpath it give me an error that it treat msg.childpath as it`s the path 

i already fixed the problem by just changing the query once function

`var QueryOnce = function(msg) {
                  console.log("from Query once",msg)
                  console.log("from Query once",node.childpath)
                  var childpath = node.childpath
                  if(childpath == "msg.childpath"){
                    if("childpath" in msg){
                      childpath = msg.childpath
                    }
                  }
                  childpath = childpath || "/"
                        firebase.database().ref(childpath).once(node.eventType.toString()).then(function (snapshot) {
                          
                                msg.payload = snapshot.val();
                                node.send(msg);
                                node.status({ fill: "green", shape: "ring", text: "Received Data(Once) at " + Utils.getTime() });
                        });
                }`

**Comment by mr-sagar-shelar** [comment]
Hi, Your changes are merged into the repo.
