### ISSUE TITLE
email auth responds AUTH IS DISABLED

### ISSUE THREAD

**Issue by gmag11** [shaggyshelar/node-red-contrib-google-firebase#5]
Hi, using email auth I get error messages. I've modified your code in order to fill more values on config used to init firebase app.
It is not fully tested but works in my side. I'm not very familiar with Firebase and node-red module creation, so please check code before merge. I'll make a pull request now.

Thank you, this module is one of two that I could make it work with authentication, and it has more features.

**Comment by mr-sagar-shelar** [comment]
Hey, your PR is merged and published on npm.

Happy Coding!!

**Comment by gmag11** [comment]
Great! Thank you!
