### ISSUE TITLE
Clean Proyect Config Node and Remove Dead Code

### ISSUE THREAD

**Issue by jgmatu** [shaggyshelar/node-red-contrib-google-firebase#8]
Hi,

I have got a good version of firebase google to pull.

 A simple Node Config and all the methods necessaries to use the google database firebase.

  I will do a pull request to a review of code and begin from here to create features to the project.

Thanks!
:)

**Comment by mr-sagar-shelar** [comment]
Sure, thanks for contributing

**Comment by mr-sagar-shelar** [comment]
Your PR is merged
